worker_db = \
{   'alchemist': {   'name': 'Alchemist',
                     'per-level': 10,
                     'skill1': 'magic',
                     'skill2': 'alchemy',
                     'skill3': 'tinkering',
                     'tier': 3},
    'armorer': {   'name': 'Armorer',
                   'per-level': 5,
                   'skill1': 'metal-working',
                   'skill2': 'armor-crafting',
                   'tier': 1},
    'artificer': {   'name': 'Artificer',
                     'per-level': 7,
                     'skill1': 'tinkering',
                     'skill2': 'armor-crafting',
                     'tier': 2},
    'artisan': {   'name': 'Artisan',
                   'per-level': 10,
                   'skill1': 'textile-working',
                   'skill2': 'arts-and-crafts',
                   'skill3': 'jewelry',
                   'tier': 3},
    'blacksmith': {   'name': 'Blacksmith',
                      'per-level': 5,
                      'skill1': 'metal-working',
                      'skill2': 'weapon-crafting',
                      'tier': 1},
    'carpenter': {   'name': 'Carpenter',
                     'per-level': 5,
                     'skill1': 'wood-working',
                     'skill2': 'weapon-crafting',
                     'tier': 1},
    'druid': {   'name': 'Druid',
                 'per-level': 5,
                 'skill1': 'wood-working',
                 'skill2': 'alchemy',
                 'tier': 1},
    'enchanter': {   'name': 'Enchanter',
                     'per-level': 7,
                     'skill1': 'magic',
                     'skill2': 'rune-writing',
                     'tier': 2},
    'fletcher': {   'name': 'Fletcher',
                    'per-level': 7,
                    'skill1': 'weapon-crafting',
                    'skill2': 'arts-and-crafts',
                    'tier': 2},
    'jeweler': {   'name': 'Jeweler',
                   'per-level': 7,
                   'skill1': 'metal-working',
                   'skill2': 'jewelry',
                   'tier': 2},
    'leatherworker': {   'name': 'Leatherworker',
                         'per-level': 5,
                         'skill1': 'textile-working',
                         'skill2': 'armor-crafting',
                         'tier': 1},
    'luthier': {   'name': 'Luthier',
                   'per-level': 7,
                   'skill1': 'wood-working',
                   'skill2': 'textile-working',
                   'tier': 2},
    'master': {   'name': 'Master',
                  'per-level': 10,
                  'skill1': 'metal-working',
                  'skill2': 'weapon-crafting',
                  'skill3': 'armor-crafting',
                  'tier': 3},
    'sculptor': {   'name': 'Sculptor',
                    'per-level': 10,
                    'skill1': 'wood-working',
                    'skill2': 'arts-and-crafts',
                    'skill3': 'jewelry',
                    'tier': 3},
    'seamstress': {   'name': 'Seamstress',
                      'per-level': 10,
                      'skill1': 'textile-working',
                      'skill2': 'arts-and-crafts',
                      'skill3': 'armor-crafting',
                      'tier': 3},
    'sorceress': {   'name': 'Sorceress',
                     'per-level': 7,
                     'skill1': 'magic',
                     'skill2': 'alchemy',
                     'tier': 2},
    'tailor': {   'name': 'Tailor',
                  'per-level': 5,
                  'skill1': 'textile-working',
                  'skill2': 'arts-and-crafts',
                  'tier': 1},
    'the-giant': {   'name': 'The Giant',
                     'per-level': 12,
                     'skill1': 'metal-working',
                     'skill2': 'weapon-crafting',
                     'skill3': 'magic',
                     'skill4': 'rune-writing',
                     'tier': 4},
    'wizard': {   'name': 'Wizard',
                  'per-level': 10,
                  'skill1': 'magic',
                  'skill2': 'alchemy',
                  'skill3': 'rune-writing',
                  'tier': 3}}