worker_db = \
{   'alchemist': {   'name': 'Alchemist',
                     'per-level': 10,
                     'skill1': ('magic', 15),
                     'skill2': ('alchemy',25),
                     'skill3': ('tinkering',20),
                     'tier': 3},
    'armorer': {   'name': 'Armorer',
                   'per-level': 5,
                   'skill1': ('metal-working', 6),
                   'skill2': ('armor-crafting', 8),
                   'tier': 1},
    'artificer': {   'name': 'Artificer',
                     'per-level': 7,
                     'skill1': ('tinkering',10),
                     'skill2': ('armor-crafting',10),
                     'tier': 2},
    'artisan': {   'name': 'Artisan',
                   'per-level': 10,
                   'skill1': ('textile-working',10),
                   'skill2': ('arts-and-crafts',30),
                   'skill3': ('jewelry',20),
                   'tier': 3},
    'blacksmith': {   'name': 'Blacksmith',
                      'per-level': 5,
                      'skill1': ('metal-working',8),
                      'skill2': ('weapon-crafting',6),
                      'tier': 1},
    'carpenter': {   'name': 'Carpenter',
                     'per-level': 5,
                     'skill1': ('wood-working',8),
                     'skill2': ('weapon-crafting',6),
                     'tier': 1},
    'druid': {   'name': 'Druid',
                 'per-level': 5,
                 'skill1': ('wood-working',4),
                 'skill2': ('alchemy',10),
                 'tier': 1},
    'enchanter': {   'name': 'Enchanter',
                     'per-level': 7,
                     'skill1': ('magic',8),
                     'skill2': ('rune-writing',12),
                     'tier': 2},
    'fletcher': {   'name': 'Fletcher',
                    'per-level': 7,
                    'skill1': ('weapon-crafting',10),
                    'skill2': ('arts-and-crafts',10),
                    'tier': 2},
    'jack-of-all-trades': {   'name': 'Fletcher',
                    'per-level': 12,
                    'skill1': ('textile-working',1),
                    'skill2': ('armor-crafting',1),
                    'skill3': ('metal-working',1),
                    'skill4': ('weapon-crafting',1),
                    'skill5': ('wood-working',1),
                    'skill6': ('alchemy',1),
                    'skill7': ('magic',1),
                    'skill8': ('tinkering',1),
                    'skill9': ('jewelry',1),
                    'skill10': ('arts-and-crafts',1),
                    'skill11': ('rune-writing',1),
                    'tier': 3},
    'jeweler': {   'name': 'Jeweler',
                   'per-level': 7,
                   'skill1': ('metal-working',10),
                   'skill2': ('jewelry',10),
                   'tier': 2},
    'leatherworker': {   'name': 'Leatherworker',
                         'per-level': 5,
                         'skill1': ('textile-working',8),
                         'skill2': ('armor-crafting',6),
                         'tier': 1},
    'luthier': {   'name': 'Luthier',
                   'per-level': 7,
                   'skill1': ('wood-working',10),
                   'skill2': ('textile-working',10),
                   'tier': 2},
    'master': {   'name': 'Master',
                  'per-level': 10,
                  'skill1': ('metal-working', 15),
                  'skill2': ('weapon-crafting', 25),
                  'skill3': ('armor-crafting', 20),
                  'tier': 3},
    'sculptor': {   'name': 'Sculptor',
                    'per-level': 10,
                    'skill1': ('wood-working',25),
                    'skill2': ('arts-and-crafts',10),
                    'skill3': ('jewelry',25),
                    'tier': 3},
    'seamstress': {   'name': 'Seamstress',
                      'per-level': 10,
                      'skill1': ('textile-working',30),
                      'skill2': ('arts-and-crafts',15),
                      'skill3': ('armor-crafting',15),
                      'tier': 3},
    'sorceress': {   'name': 'Sorceress',
                     'per-level': 7,
                     'skill1': ('magic',8),
                     'skill2': ('alchemy',12),
                     'tier': 2},
    'tailor': {   'name': 'Tailor',
                  'per-level': 5,
                  'skill1': ('textile-working',6),
                  'skill2': ('arts-and-crafts',8),
                  'tier': 1},
    'the-giant': {   'name': 'The Giant',
                     'per-level': 12,
                     'skill1': ('metal-working',25),
                     'skill2': ('weapon-crafting',25),
                     'skill3': ('magic',25),
                     'skill4': ('rune-writing',25),
                     'tier': 4},
    'wizard': {   'name': 'Wizard',
                  'per-level': 10,
                  'skill1': ('magic',15),
                  'skill2': ('alchemy',20),
                  'skill3': ('rune-writing',25),
                  'tier': 3}}